### PR TITLE
Added groupsData object, added `event` event, added gid to announcement event

### PR DESCRIPTION
**Pull request by DoctorMcKay**

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
Rebased for 0.6.8.

**Comment by mcd1992** [comment]
Would love to see this PR merged. Currently in need of a means to get group names from their groupid.

**Comment by Efreak** [comment]
Yay. A fix for #85. Hope it eventually gets merged, I'm too lazy to add this to my own code.

**Comment by seishun** [comment]
Added in master as [`clanStates`](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#clanstates) and ['clanState'](https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#clanstate).

**Pull request closed without merging**
