### PR TITLE
add gameInvite event on friends

### PR DESCRIPTION
**Pull request by samthor**
I'm using 'invite to game' as a signal for something.

### CODE REVIEW

**Comment by andrewda** [comment]
👍 

might want to return the user's steamid, even if there's no info about the user.

**Comment by scholtzm** [comment]
Just fyi, you can also use the [`'message'/send`](https://github.com/seishun/node-steam#messagesend) interface to cleanly add this functionality to your project.

**Comment by samthor** [comment]
@scholtzm I know, I've done that :)

**Comment by seishun** [comment]
Thanks, but I would prefer to have just the basic functionality (adding friends/removing friends/chat) in the SteamFriends handler. Perhaps you would be interested in publishing a module for game-related friends functionality? (inviting to a game, watching a game, joining a game, etc.)

**Pull request closed without merging**
