### PR TITLE
Update servers.js

### PR DESCRIPTION
**Pull request by Triniayo**
New Steam servers.

### CODE REVIEW

**Comment by seishun** [comment]
Where is this list from?

**Comment by Triniayo** [comment]
From the official API.

**Comment by seishun** [comment]
SteamKit2 is considering reintroducing a bootstrapped list (https://github.com/SteamRE/SteamKit/pull/597#issuecomment-428130452). If they do, I'll use their list. Otherwise I think I'll get rid of servers.js and use cm0.steampowered.com (which works most of the time) by default and try to make it clearer that one should really handle the 'servers' event (as if the code in example.js weren't enough).

**Comment by seishun** [comment]
Thank you for your contribution. I chose a different approach in https://github.com/seishun/node-steam/commit/8f0f68bc244bc02fd38c585bbe956b9546c562a0. Instead of hard-coding a server list, it is downloaded automatically when installing from git and is (will be) bundled only in the npm package.

**Pull request closed without merging**
