### PR TITLE
Added example for auto-accepting new friend requests.

### PR DESCRIPTION
**Pull request by brutalhonesty**
Noticed the relationships event wasn't immediately clear and thought this might help new-comers.

### CODE REVIEW

**Comment by brutalhonesty** [comment]
Sorry but its been years since I've touched this project.

I would assume it runs about the same:
http://kopy.io/4L6vO

**Comment by scholtzm** [comment]
https://github.com/seishun/node-steam/tree/master/lib/handlers/friends#friends

Client doesn't have `friends` property.

**Comment by brutalhonesty** [comment]
Like I said, I haven't worked with this project in years. If you would be so kind as to provide an example @scholtzm of what @rbJARB is looking for.

**Comment by scholtzm** [comment]
2 things need to be changed:

* `friends` is now property of `SteamFriends` handler
* `PendingInvitee` is obsolete; use `RequestRecipient` instead

**Example:**
https://github.com/scholtzm/vapor/blob/master/lib/plugins/essentials.js#L45-L49

This pull request should be closed imho.

**Comment by brutalhonesty** [comment]
So it shall be. Thanks!

**Comment by rbJARB** [comment]
Thanks very much. Much appreciated :smile:

**Pull request closed without merging**
