### PR TITLE
Added PICS

### LINKED ISSUE #40: Feature Request: ChangeSets functionality
Hi,

I would be extremely grateful if you could add a way to receive changesets..

I was attempting to do this via toGC/fromGC but as you told me, that's not what we are supposed to use..

To be more specific, looking for PICSChangesSinceRequest/PICSChangesSinceResponse I believe (I think the response is the callback)

Thanks

### PR DESCRIPTION
**Pull request by DoctorMcKay**
Resolves #40 and #91.

### CODE REVIEW

**Comment by paralin** [comment]
+1

**Comment by jabbink** [comment]
:+1: but this needs a rebase I guess.

**Comment by DoctorMcKay** [comment]
Rebased and updated for 0.6.8.

**Comment by paralin** [comment]
+1 (again) :)

**Pull request closed without merging**
