### PR TITLE
Add the ability to specify a custom socket

### PR DESCRIPTION
**Pull request by paralin**
As per your complaints on my PR #131 I have implemented the ability to specify a custom socket object. There are minimal code changes (about 3 lines, not including the indenting). I've tested the code using the example as well as my own projects, and there is no impact on existing code.

### CODE REVIEW

**Comment by seishun** [comment]
Can you provide a use case for using proxy?

**Comment by paralin** [comment]
If you're working with a lot of accounts and want to proxy for... various reasons

I've found a better solution than using proxies though, and this code is really rough. I'm going to abandon this for now.

**Comment by jabbink** [comment]
> If you're working with a lot of accounts and want to proxy for... various reasons

I am working with many different accounts. They are all legitimately my accounts and have occasionally been trade banned (sometimes scammers dump items to one of my accounts when my code can't find any suspicious activities for those items/accounts via steamrep and other sources) and subsequently (and insanely fast) unbanned by Steam Support (<1 day) even though I clearly stated that this involved automatic trading bots in the Support Ticket. Never lost an account or a whole batch of accounts with this; acting from only two different IP addresses.

So I'm not sure why you would need this, but it doesn't sound as if what you're doing is allowed by the Steam EULA (hell, what I'm doing is in a gray area or even forbidden and even my accounts never got perma banned).

**Comment by paralin** [comment]
I have explicit permission at this point for what I'm doing so it's no longer relevant. There doesn't seem to be any built-in IP limits, though.

At the time I was doing this due to Dota 2 restrictions on requests per IP for replays, however, these days it's easy enough with the cloud to grab a new IP address when needed.

**Comment by overheader** [comment]
For me blocked 10 accounts, here support does not answer already about two months, I do not know that to do.

**Pull request closed without merging**
