### PR TITLE
Add ability to bind to custom IP for connections

### PR DESCRIPTION
**Pull request by DoctorMcKay**

### CODE REVIEW

**Comment by seishun** [comment]
What's your use case for this?

**Comment by DoctorMcKay** [comment]
Choosing your interface is a pretty rudimentary part of networking. 

Regardless, I want to change my public IP to avoid rate limiting.

**Comment by seishun** [comment]
>Regardless, I want to change my public IP to avoid rate limiting. 

Fair enough. What about `localPort` though?

**Comment by DoctorMcKay** [comment]
There because it's there. Could be used for firewalls.

The Steam Client used by gameservers allows you to specify a `-steamport` command-line parameter.

**Comment by jabbink** [comment]
:+1:

**Comment by DoctorMcKay** [comment]
:-1: it doesn't apply to reconnections.

**Comment by seishun** [comment]
This is unintuitive because it looks like you're connecting to the specified IP address and port. I suggest using an object instead, assuming this is still relevant to you. If not, feel free to close it.

**Comment by DoctorMcKay** [comment]
It's no longer relevant to me, so I'll go ahead and close it.

**Pull request closed without merging**
